#! /bin/sh
# admin/commit [ "alt" ] [ -t | -n ] [[ -m ] "text" ] [ other cvs-args ]
# mit "alt" als erstem parm wird versionsnummer nicht weitergezaehlt

# CVS program name
p=f4a
# top dir
d=$(dirname $(dirname ${0}))
# CVS-dir
c=/var/lib/cvs

export CVSROOT="${c}"

# -------------------------------------------------------------- 

[ "${1}" = "alt" ]&&shift&&alt=alt
t=${1}
[ "${t}" = "-t" ]&&{ shift;t=; }||{ [ "${t}" = "-n" ]&&{ shift;t=; }||t="-t"; }

g=$(${d}/a/relse.sh r.v.x.t)

[ "${alt}" = "alt" ]||${d}/a/relse.sh t+
[ "${1}" = "-m" ]&&shift

cvs -d${c} commit -m "$(${d}/a/relse.sh):$(${d}/a/relse.sh t) ${1}"
[ "${t}" = "-t" -a -z "${alt}" ]&&cvs -d${c} rtag -bRf tag-${g} ${p}&&echo TAG is \"tag-${g}\"|tee ./d/LATEST-CVS
